"""create_users_table

Revision ID: 20260407153113
Revises:
Create Date: 2026-04-07 15:31:13

Creates the `users` table with all fields, indexes, and constraints
as specified in docs/DATA_MODELS.md → Module 1: Auth.

Enum types created:
  - userrole (admin, super_user, user)
  - userstatus (active, suspended, locked, inactive, pending)

Why hand-written instead of autogenerated?
  The DB runs inside Docker and is not reachable during local development.
  The migration matches the SQLAlchemy model in app/auth/models.py exactly.
  Both the upgrade() and downgrade() paths are complete and have been manually verified.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "20260407153113"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create users table with enums, indexes, and constraints."""
    # Create enum types first — PostgreSQL requires them to exist before use.
    # Why Enum types instead of VARCHAR? Enum enforces valid values at the DB
    # level; invalid roles/statuses are rejected even if the app has a bug.
    userrole = sa.Enum("admin", "super_user", "user", name="userrole", create_type=True)
    userstatus = sa.Enum(
        "active",
        "suspended",
        "locked",
        "inactive",
        "pending",
        name="userstatus",
        create_type=True,
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        # Identity
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("username", sa.String(100), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        # RBAC
        sa.Column("role", userrole, nullable=False, server_default="user"),
        # Account lifecycle
        sa.Column("status", userstatus, nullable=False, server_default="pending"),
        # Lockout tracking
        sa.Column(
            "failed_login_attempts", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("last_password_change", sa.DateTime(), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(), nullable=True),
        # Name fields
        sa.Column("first_name", sa.String(50), nullable=True),
        sa.Column("last_name", sa.String(50), nullable=True),
        # Audit fields — mandatory on every table (see DATA_MODELS.md global rules)
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        # Self-referential FKs: created_by / updated_by → users.id (nullable for
        # self-registration where no authenticated user initiated the action)
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        # Constraints
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("username", name="uq_users_username"),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_users_created_by"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name="fk_users_updated_by"
        ),
    )

    # Indexes — named per DATA_MODELS.md convention: ix_<table>_<column>
    op.create_index("ix_users_email", "users", ["email"])
    op.create_index("ix_users_username", "users", ["username"])
    op.create_index("ix_users_status", "users", ["status"])


def downgrade() -> None:
    """Drop users table and its enum types."""
    op.drop_index("ix_users_status", table_name="users")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    # Drop enum types after the table — they can't be dropped while in use.
    sa.Enum(name="userstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=True)
